processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-20:
created: object(1,0), object(1,1), object(1,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10936400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 22-24:
created: object(2,0)
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 4332000,  storage_rebate: 2979504, non_refundable_storage_fee: 30096

task 3 'view-object'. lines 26-26:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: sui::coin::Coin<test::fake::FAKE> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    balance: sui::balance::Balance<test::fake::FAKE> {
        value: 100u64,
    },
}

task 4 'programmable'. lines 28-30:
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: Some("Coins do not have the same type"), command: Some(1) } }

task 5 'programmable'. lines 32-33:
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: Some("Coins do not have the same type"), command: Some(0) } }

task 6 'programmable'. lines 36-39:
Error: Transaction Effects Status: Invalid command argument at 2. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 2, kind: TypeMismatch }, source: Some("Coins do not have the same type"), command: Some(2) } }

task 7 'programmable'. lines 41-44:
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: Some("Coins do not have the same type"), command: Some(2) } }
